spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chantierpro_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        
  # Flyway configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  
  # CORS Configuration
  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      exposed-headers: "Access-Control-Allow-Origin,Access-Control-Allow-Credentials"
  
  # Bean Configuration
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  servlet:
    context-path: /api
  # Additional CORS headers in HTTP response
  compression:
    enabled: true

logging:
  level:
    com.chantierpro: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    org.springframework.security: DEBUG